version: "3.7"
services:
    front-end:
        image: front-end:encurlta
        ports:
            - "3000:3000"
        environment: 
            NODE_ENV: development
        command: npm start
    back-end:
        image: back-end:encurlta
        ports: 
            - "5000:5000"
        environment:
            NODE_ENV: development
        command: npm start

        